name: release

on:
  workflow_run:
    workflows: ["build"]
    branches: [master]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Release Fix
        if: contains(github.event.head_commit.message, '@RELEASE_MINOR') == false
        run: echo ${{ github.event.head_commit.message }} |
             echo Releasing fix!
      - name: Release Minor
        if: contains(github.event.head_commit.message, '@RELEASE_MINOR')
        run: echo ${{ github.event.head_commit.message }} |
             echo Releasing minor!
        
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v2
      - name: Failed
        run: echo Releas canceled!
